name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python       # to setup python for workflow
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Running basic test
      run: |
        echo "n trest are added!"

